#imports_granularity = "Crate" #Unstable features are only available in nightly channel. Uncheck this if you are using nightly channel only.
#group_imports = "One" #Unstable features are only available in nightly channel. Uncheck this if you are using nightly channel only.
tab_spaces = 2
edition = "2024"
style_edition = "2024"